version: "3.4"
services: 
    identitiy-net-core-starter:
      image: identity-net-core:starter
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5080:80"
        - "5443:443"
      environment:
        - ASPNETCORE_HTTPS_PORT=443
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_Kestrel__Certificates__Default__Password=development
      volumes:
        - ${USERPROFILE}\.aspnet\https:/https/:ro