version: "3.4"
services: 
    identity-net-core-starter:
      image: identity-net-core:starter
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5080:80"
        - "5443:443"
      environment:
        - ASPNETCORE_HTTPS_PORT=443
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dotnet-devcert.pfx
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_Kestrel__Certificates__Default__Password=
        - IDENTITY_CONTEXT=Server=identity-store,1433;Database=IdentityDb;user=SA;password="Unk0wnAga1n";
        - EMAIL_ACCOUNT=,
        - EMAIL_PASSWORD=,
        - EMAIL_HOST=,
        - EMAIL_PORT=
#      volumes:
#        - ./aspnet/https:/https:ro
#        - ./aspnet/https/dotnet-devcert.pfx:/https/dotnet-devcert.pfx:ro

    identity-store:
      image: mcr.microsoft.com/mssql/server
      environment:
        SA_PASSWORD: "Unk0wnAga1n"
        ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"